In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt
%matplotlib inline
df = pd.read_csv("loanP_train.csv") #reading the dataset in a dataframe using pandas

In [2]:
df.head() # look at few top rows by using the function head()

,Loan_ID,Gender,Marital_Status,Dependents,Graduate,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LI0100,Male,Single,0,Yes,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LI0101,Male,Married,1,Yes,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LI0102,Male,Married,0,Yes,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LI0103,Male,Married,0,No,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LI0104,Male,Single,0,Yes,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [3]:
df.describe() # look at a summary

,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History
count,599.000000,599.000000,578.000000,585.000000,550.00000
mean,5420.687813,1563.913055,145.434256,342.461538,0.84000
std,6169.168633,2456.618360,84.596463,64.868352,0.36694
min,150.000000,0.000000,9.000000,12.000000,0.00000
25%,2874.000000,0.000000,100.000000,360.000000,1.00000
50%,3812.000000,1210.000000,126.500000,360.000000,1.00000
75%,5807.500000,2279.000000,165.000000,360.000000,1.00000
max,81000.000000,33837.000000,700.000000,480.000000,1.00000

In [59]:
df.boxplot(column = 'ApplicantIncome', by='Graduate') #to understand the distribution

In [4]:
df["ApplicantIncome"].hist(bins=50) #there are some extreme values

In [66]:
temp1 = df['Credit_History'].value_counts(ascending=True) 
temp2 = df.pivot_table(values='Loan_Status' , index=['Credit_History'],aggfunc=lambda x: x.map({'Y':1, 'N':0}).mean()) 
print('Frequency Table for Credit History:') 
print(temp1) 

print('\nProbility of getting loan for each Credit History class:')

Frequency Table for Credit History:
Credit_History
0.0     88
1.0    462
Name: count, dtype: int64

Probility of getting loan for each Credit History class:

temp1 = df['Credit_History'].value_counts(ascending=True)
temp2 = df.pivot_tables(values='Loan_Status' , index=['Credit_History'],aggfunc=lambda x: x.map({'Y':1, 'N':0}).mean())
print('Frequency Table for Credit History:')
print(temp1)
print('\nProbility of getting loan for each Credit History class:')

In [5]:
import matplotlib.pyplot as plt
fig = plt.figure(figsize=(8,4))
ax1 = fig.add_subplot(121)
ax1.set_xlabel('Credit_History')
ax1.set_ylabel('Count of Applicants')
ax1.set_title('Applicants by Credit_History')
temp1.plot(kind='bar')

[]

In [6]:
df.apply(lambda x: sum(x.isnull()), axis=0) # number of missing values in each column

Loan_ID               0
Gender               13
Marital_Status        3
Dependents           15
Graduate              0
Self_Employed        30
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           21
Loan_Amount_Term     14
Credit_History       49
Property_Area         0
Loan_Status           0
dtype: int64

In [25]:
df.fillna({'LoanAmount': df['LoanAmount'].mean()}, inplace=True)

In [ ]:
df.apply(lambda x: sum(x.isnull()), axis=0)

In [68]:
df.fillna({'Loan_Amount_Term': df['Loan_Amount_Term'].mean()}, inplace=True)
df.fillna({'Credit_History': df['Credit_History'].mean()}, inplace=True) #Filling missing

In [27]:
df.dtypes

Loan_ID               object
Gender                object
Marital_Status        object
Dependents            object
Graduate              object
Self_Employed         object
ApplicantIncome        int64
CoapplicantIncome    float64
LoanAmount           float64
Loan_Amount_Term     float64
Credit_History       float64
Property_Area         object
Loan_Status           object
dtype: object

In [74]:
# Import models from scikit learn module:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import KFold
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier, export_graphviz
from sklearn import metrics

In [76]:
# extracting only the independent variables
x = df.iloc[:, [8,10]].values #credit history and loan amount
#exracting only the dependent variables
y = df.iloc[:, 12].values #loan status

In [78]:
#splitting the dataset into the training set and test set
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split (x,y,test_size = 0.25, random_state = 0)

In [80]:
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
x_train = sc_x.fit_transform(x_train)
x_test = sc_x.transform(x_test)

In [82]:
#fitting logistics regression to training dataset
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(x_train,y_train)

LogisticRegression(random_state=0)

In [84]:
# Predicting the test set results
y_pred = classifier.predict(x_test)
y_pred

array(['Y', 'N', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y',
       'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y',
       'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y',
       'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N',
       'Y', 'Y', 'N', 'N', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y',
       'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y',
       'Y', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y',
       'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y',
       'Y', 'N', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y',
       'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'Y', 'N', 'Y', 'Y',
       'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y',
       'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y'], dtype=object)

In [55]:
# building the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

NameError: name 'y_test' is not defined

In [57]:
from sklearn.metrics import accuracy_score 
accuracy_score(y_test, y_pred)

NameError: name 'y_test' is not defined

In [31]:
one = pd.DataFrame(np.random.randn(5,4)) 
one

          0         1         2         3
0 -0.995677 -0.531009  0.328147  0.812048
1  1.697066  1.077628 -1.214475  1.665256
2 -0.158246 -0.125127 -0.328860  0.411681
3 -0.696215  1.899908  0.756724 -0.572908
4  2.320043  2.659178 -0.752857 -1.782054

In [33]:
two = pd.DataFrame(np.random.randn(5,4))
two

          0         1         2         3
0  0.373872 -0.266446 -0.742663  1.789550
1 -2.474375  0.423133  0.162332  1.109683
2 -1.467657  0.515814 -1.240445  0.275961
3  1.190669 -0.460179 -0.558380 -1.150722
4 -1.354575  0.765764  1.010257  2.644636

In [35]:
pd.concat([one,two])

          0         1         2         3
0 -0.995677 -0.531009  0.328147  0.812048
1  1.697066  1.077628 -1.214475  1.665256
2 -0.158246 -0.125127 -0.328860  0.411681
3 -0.696215  1.899908  0.756724 -0.572908
4  2.320043  2.659178 -0.752857 -1.782054
0  0.373872 -0.266446 -0.742663  1.789550
1 -2.474375  0.423133  0.162332  1.109683
2 -1.467657  0.515814 -1.240445  0.275961
3  1.190669 -0.460179 -0.558380 -1.150722
4 -1.354575  0.765764  1.010257  2.644636

In [37]:
left = pd.DataFrame({'key': ['foo', 'bar'], '1va1': [1,2]})
left

   key  1va1
0  foo     1
1  bar     2

In [41]:
right = pd.DataFrame({'key': ['foo', 'bar', 'bar'], 'rva1': [3, 4, 5]})
right

   key  rva1
0  foo     3
1  bar     4
2  bar     5

In [43]:
pd.merge(left, right, on='key')

   key  1va1  rva1
0  foo     1     3
1  bar     2     4
2  bar     2     5